apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-secret
  labels:
    type: backend
data:
  DATABASE_URL: postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@postgres:5432/{{ .Values.database.name }}
