apiVersion: v1
kind: Service
metadata:
  name: todomvc-backend
  labels:
    type: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.containerPort }}
  selector:
    type: backend