apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-frontend
  labels:
    type: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox
          args:
            - /bin/sh
            - -c
            - |
              until nc -z -v -w30 todomvc-backend {{ .Values.backend.service.containerPort }}; do
                echo waiting for backend service...
                sleep 3s
              done
      containers:
        - name: todomvc-frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.frontend.service.containerPort }}