apiVersion: v1
kind: Service
metadata:
  name: todomvc-frontend
  labels:
    type: frontend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.service.containerPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      name: todomvc-frontend
  selector:
    type: frontend