apiVersion: v1
kind: Service
metadata:
  name: todomvc-backend
  labels:
    type: backend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: todomvc-backend
  selector:
    type: backend