apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-backend
  labels:
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:14
          env:
          - name: PGHOST
            value: postgres
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: postgres-secret
          - name: PGPASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secret
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: postgres-secret
          command:
            - /bin/sh
            - -c
            - |
              while ! psql -c 'select 1' > /dev/null 2>&1; do
                echo "waiting for database"
                sleep 3s
              done
              echo "database is ready!"
        - name: todomvc-migration
          image: todomvc/backend:latest
          imagePullPolicy: Never
          command: [ 'npm', 'run', 'migrate:prod' ]
          envFrom:
            - configMapRef:
                name: backend-secret
      containers:
        - name: todomvc-backend
          image: todomvc/backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-secret          