apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-frontend
  labels:
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: todomvc-frontend
          image: todomvc/frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80