apiVersion: v1
kind: Service
metadata:
  name: todomvc-frontend
  labels:
    type: frontend
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: todomvc-frontend
  selector:
    type: frontend
  type: NodePort