apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-frontend
  labels:
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox
          args:
            - /bin/sh
            - -c
            - |
              until nc -z -v -w30 todomvc-backend 3001; do
                echo waiting for backend service...
                sleep 3s
              done
      containers:
        - name: todomvc-frontend
          image: todomvc/frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80