apiVersion: v1
kind: Service
metadata:
  name: todomvc-react
  labels:
    app: todomvc-react
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: todomvc-react
  selector:
    app: todomvc-react
  type: NodePort